/**
 * Generates src/generated/system-prompt.ts with the OpenUI Lang system prompt
 * baked in as a static string. Run with: pnpm generate
 *
 * Re-run after upgrading @openuidev/react-ui.
 */
import { mkdirSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { openuiChatLibrary, openuiChatPromptOptions } from "@openuidev/react-ui/genui-lib";

const __dirname = dirname(fileURLToPath(import.meta.url));
const prompt = openuiChatLibrary.prompt(openuiChatPromptOptions);

const output = `// Generated by \`pnpm generate\` — do not edit manually.
// Re-run after upgrading @openuidev/react-ui.
export const SYSTEM_PROMPT = ${JSON.stringify(prompt)};
`;

const outDir = join(__dirname, "src", "generated");
mkdirSync(outDir, { recursive: true });
const outPath = join(outDir, "system-prompt.ts");
writeFileSync(outPath, output, "utf8");
console.log(`✓ Wrote ${outPath} (prompt: ${prompt.length} chars)`);
