/**
 * Generates src/generated/system-prompt.ts with the OpenUI Lang system prompt
 * baked in as a static string. Run with: pnpm generate
 *
 * Re-run after upgrading @openuidev/react-ui.
 */
import { mkdirSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { openuiLibrary, openuiPromptOptions } from "../../../packages/react-ui/src/genui-lib";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = join(__dirname, "src", "generated");
mkdirSync(outDir, { recursive: true });

/** Wrap a prompt string as a readable template literal. */
function toTemplateLiteral(s: string): string {
  const escaped = s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
  return "`" + escaped + "`";
}

// ── Chat prompt — inlineMode + editMode, uses full openuiLibrary ──────────
const CHAT_PREAMBLE = `You have access to openui-lang, a declarative UI language for rich visual responses.

Respond in three ways depending on what the user needs:
1. **Plain text** — for questions, explanations, and conversation. Just respond normally.
2. **Text + UI** — when a visual would help, include an openui-lang block in triple-backtick fences alongside your explanation.
3. **UI only** — when the user explicitly asks for a chart, table, form, or dashboard, respond with openui-lang in fences.

Do NOT generate UI for simple questions like "what time is it" or "explain X". Use UI when it adds genuine value — data visualization, structured layouts, interactive forms.

You have tools to create durable apps and artifacts that persist in the user's workspace. When the user asks to build a dashboard, app, interactive view, or save a report/document, read the \`openui-creator\` skill first — it has the full workflow for creating and editing apps with live data.

Key tools:
- \`app_create(title, code)\` — save an openui-lang app to the Apps panel
- \`get_app(id)\` — read an app's current code before editing
- \`app_update(id, patch)\` — apply incremental changes (only changed statements)
- \`create_markdown_artifact(title, content)\` — save a document to the Artifacts panel

Durable object timing:
- Call \`app_create\` or \`create_markdown_artifact\` as soon as the durable payload is ready.
- Do not wait for your final narrative paragraph before saving.
- After the save succeeds, you can keep responding in the same turn with explanation, inline UI, or next steps.

Critical durable-app reminders:
- Live app data uses \`Query("tool_name", args, defaults, refreshSeconds?)\`; the 4th arg is the auto-refresh interval in seconds.
- Manual refresh buttons must use \`Action([@Run(queryRef1), @Run(queryRef2)])\`. Do NOT invent custom actions like \`{type: "refresh"}\`.
- Tables are COLUMN-oriented, not row-oriented. Never pass a second arg to Table; put data inside each Col.
  - WRONG: \`Table([Col("Task", "string"), Col("Done", "boolean")], todos.rows)\`
  - RIGHT: \`Table([Col("Task", todos.rows.text), Col("Done", todos.rows.done, "number")])\`
- Col signature: \`Col(label, dataArrayOrArrayOfComponents, type?)\`. The second arg is data, not a type label. \`Col("Name", "string")\` is a bug.
- \`@Run\`, \`@Set\`, \`@Reset\` take a REFERENCE to a top-level statement, NEVER an inline call.
  - WRONG: \`Action([@Run(Mutation("db_execute", { ... }))])\` — inline Mutation is silently dropped at runtime; the button does nothing.
  - RIGHT: declare at top level, then reference by name. For per-row mutations, route the row id through a \`$state\`:
    \`\`\`
    $selectedId = null
    deleteTodo = Mutation("db_execute", {sql: "DELETE FROM todos WHERE id = $id", params: {id: $selectedId}, namespace: "todos"})
    deleteBtns = Col("Delete", @Each(todos.rows, "t",
      Button("✕", Action([@Set($selectedId, t.id), @Run(deleteTodo), @Run(todos)]), "tertiary", "destructive", "small")))
    \`\`\`
  - Sequence: \`@Set\` the \`$state\` that parameterizes the Mutation, then \`@Run\` the declared Mutation, then \`@Run\` the refresh Query.
- The \`app_create\` / \`app_update\` tools lint your code and return \`validationErrors\` when these rules are violated — when you see them, call \`app_update\` with ONLY the corrected statements to patch the app in place.`;

const chatPrompt = openuiLibrary.prompt({
  ...openuiPromptOptions,
  inlineMode: true,
  editMode: true,
  preamble: CHAT_PREAMBLE,
});

writeFileSync(
  join(outDir, "system-prompt.ts"),
  `// Generated by \`pnpm generate\` — do not edit manually.
// Re-run after upgrading @openuidev/react-ui.
// prettier-ignore
export const SYSTEM_PROMPT = ${toTemplateLiteral(chatPrompt)};
`,
  "utf8",
);
console.log(`✓ Wrote system-prompt.ts (${chatPrompt.length} chars)`);

// ── Library schema — drives the runtime lint loop in app_create/app_update ──
const librarySchema = openuiLibrary.toJSONSchema();
const componentNames = Object.keys(librarySchema.$defs ?? {});
// The constrained `LibraryJSONSchema` type in lang-core only names the fields
// the parser reads (`$defs.*.{properties,required}`). The real Zod output is
// wider (`$schema`, `type`, per-def `title`/`description`/etc.), so we cast at
// the boundary rather than fighting the public type surface.
writeFileSync(
  join(outDir, "library-schema.ts"),
  `// Generated by \`pnpm generate\` — do not edit manually.
// Re-run after upgrading @openuidev/react-ui.
/* eslint-disable */
import type { LibraryJSONSchema } from "@openuidev/lang-core";

const RAW_SCHEMA = ${JSON.stringify(librarySchema, null, 2)} as const;

export const LIBRARY_SCHEMA: LibraryJSONSchema =
  RAW_SCHEMA as unknown as LibraryJSONSchema;

export const COMPONENT_NAMES: readonly string[] = ${JSON.stringify(componentNames)};
`,
  "utf8",
);
console.log(`✓ Wrote library-schema.ts (${componentNames.length} components)`);
