/**
 * Generates src/generated/system-prompt.ts with the OpenUI Lang system prompt
 * baked in as a static string. Run with: pnpm generate
 *
 * Re-run after upgrading @openuidev/react-ui.
 */
import { mkdirSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { openuiLibrary, openuiPromptOptions } from "@openuidev/react-ui/genui-lib";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = join(__dirname, "src", "generated");
mkdirSync(outDir, { recursive: true });

/** Wrap a prompt string as a readable template literal. */
function toTemplateLiteral(s: string): string {
  const escaped = s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
  return "`" + escaped + "`";
}

// ── Chat prompt — inlineMode + editMode, uses full openuiLibrary ──────────
const CHAT_PREAMBLE = `You have access to openui-lang, a declarative UI language for rich visual responses.

Respond in three ways depending on what the user needs:
1. **Plain text** — for questions, explanations, and conversation. Just respond normally.
2. **Text + UI** — when a visual would help, include an openui-lang block in triple-backtick fences alongside your explanation.
3. **UI only** — when the user explicitly asks for a chart, table, form, or dashboard, respond with openui-lang in fences.

Do NOT generate UI for simple questions like "what time is it" or "explain X". Use UI when it adds genuine value — data visualization, structured layouts, interactive forms.

You have tools to create durable apps and artifacts that persist in the user's workspace. When the user asks to build a dashboard, app, interactive view, or save a report/document, read the \`openui-creator\` skill first — it has the full workflow for creating and editing apps with live data.

Key tools:
- \`app_create(title, code)\` — save an openui-lang app to the Apps panel
- \`get_app(id)\` — read an app's current code before editing
- \`app_update(id, patch)\` — apply incremental changes (only changed statements)
- \`create_markdown_artifact(title, content)\` — save a document to the Artifacts panel

Durable object timing:
- Call \`app_create\` or \`create_markdown_artifact\` as soon as the durable payload is ready.
- Do not wait for your final narrative paragraph before saving.
- After the save succeeds, you can keep responding in the same turn with explanation, inline UI, or next steps.`;

const chatPrompt = openuiLibrary.prompt({
  ...openuiPromptOptions,
  inlineMode: true,
  editMode: true,
  preamble: CHAT_PREAMBLE,
});

writeFileSync(
  join(outDir, "system-prompt.ts"),
  `// Generated by \`pnpm generate\` — do not edit manually.
// Re-run after upgrading @openuidev/react-ui.
// prettier-ignore
export const SYSTEM_PROMPT = ${toTemplateLiteral(chatPrompt)};
`,
  "utf8",
);
console.log(`✓ Wrote system-prompt.ts (${chatPrompt.length} chars)`);
